import os
import sys
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# ==========================================
# PATH FIX: TELL PYTHON WHERE 'src' LIVES
# ==========================================
ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

load_dotenv(ROOT_DIR / ".env")
from langsmith import Client

PROJECT_NAME = os.environ.get("LANGCHAIN_PROJECT", "Biology_GraphRAG_Prod")
client = Client()

def main():
    print(f"🔌 Analyzing Tool & Integration Reliability for: {PROJECT_NAME}...\n")
    
    try:
        # Fetch recent LLM runs (specifically looking at the model's outputs)
        llm_runs = list(client.list_runs(
            project_name=PROJECT_NAME,
            run_type="llm",
            error=False,
            limit=100
        ))
    except Exception as e:
        print(f"❌ Failed to fetch runs: {e}")
        return

    tool_data = []

    for run in llm_runs:
        if not run.outputs:
            continue
            
        # Extract the message generated by the LLM
        generation = run.outputs.get("generations", [{}])[0].get("message", {})
        
        # Check if the LLM attempted to use a tool (tool_calls array exists)
        tool_calls = generation.get("kwargs", {}).get("tool_calls", [])
        
        for tool in tool_calls:
            tool_name = tool.get("name", "unknown_tool")
            tool_args = tool.get("args", {})
            
            # Check if the LLM hallucinated arguments or left required fields blank
            # (A simplistic check: if args is empty but the tool was called, it might be malformed)
            is_malformed = len(tool_args) == 0 
            
            tool_data.append({
                "trace_id": str(run.id),
                "tool_name": tool_name,
                "is_malformed": is_malformed,
                "latency_seconds": (run.end_time - run.start_time).total_seconds() if run.end_time else 0
            })

    if not tool_data:
        print("No tool calls found in the recent traces. The agent relied entirely on its internal knowledge or standard routing.")
        return

    # Load into Pandas for analysis
    df = pd.DataFrame(tool_data)
    total_calls = len(df)
    malformed_calls = df['is_malformed'].sum()
    
    print("==================================================")
    print("🛠️ TOOL INTEGRATION HEALTH REPORT")
    print("==================================================")
    print(f"Total External Tools Called: {total_calls}")
    print(f"Malformed Payloads (Agent failed to format JSON): {malformed_calls} ({(malformed_calls/total_calls)*100:.1f}%)")
    
    print("\n📊 Tool Usage Breakdown:")
    tool_counts = df['tool_name'].value_counts()
    for name, count in tool_counts.items():
        print(f"  - {name}: Triggered {count} times")
        
    print(f"\n⏱️ Average Tool Reasoning Latency: {df['latency_seconds'].mean():.2f} seconds")
    print("==================================================")

if __name__ == "__main__":
    main()